.\" (C) Copyright 2016 Vit Mojzis, vmojzis@redhat.com
.\" 
.\" This program is distributed under the terms of the GNU General Public License
.\" 
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH seextract_cil 1 2017-02-09 "" "SELinux Policy Analysis Tool"
.SH NAME
\fBseextract_cil \fP- SELinux policy graph export tool
.SH SYNOPSIS
.nf
.fam C
\fBseextract_cil\fP

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
Extracts type names from policy packages installed in the system and saves them in domain_groups_cil.conf. This gives the analysis tool information about types (which package does a type belong to and is it process or resource type).
.SH SEE ALSO
\fBsebuild_graph\fP(1), \fBseexport_graph\fP(1), \fBsegraph_query\fP(1), \fBsevisual_query\fP(1)
.SH AUTHOR
Vit Mojzis <vmojzis@redhat.com>
